#!/bin/sh
[ ! -f ~/.cache/emoji.txt ] && (curl https://raw.githubusercontent.com/mirsella/emoji-selector/master/emoji.txt -o ~/.cache/emoji.txt || echo "couldn't get the emoji list")
cat ~/.cache/emoji.txt | rofi -dmenu -i -l 30 | cut -d' ' -f1 | xargs -r xdotool type
